version: '2.4'

services:
  postfix:
    container_name: postfix
    build:
      context: .
    restart: unless-stopped
    environment:
      - POSTFIX_HOSTNAME=mail.example.com
      - POSTFIX_RELAYSERVER=smtp.mail.com
      - POSTFIX_RELAYUSER=me@mail.com
      - POSTFIX_RELAYPASS=123456
    ports:
      - 25:25/tcp
